### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by picknchew**
Refactoring
Swig -> Handlebars
ExpressJS 3 -> ExpressJS 4

### CODE REVIEW

**Comment by aramperes** [comment]
Great work :)

Although my `nodejs` branch was more of an experiment, I'm glad you expanded on it to make it much better.

@mastercoms @gdude2002 are we OK to make Shine in NodeJS? If so, we can merge this PR into master and start from there.

**Comment by gdude2002** [comment]
I'll be honest with you, I don't like Node and I don't want this project to be written in Node.

If you're happy to work on it yourself, that's fine, but I won't be able to help you if you decide to stick with it. Up to you, imo.

**Review by gdude2002 — DISMISSED** [review]
I don't like Node. If I'm to approve this, I'd like acknowledgement from everyone involved that they're OK with me not being able to provide any assistance.

**Review by mastercoms — APPROVED** [review]

**Comment by gdude2002** [comment]
_You're not everyone involved_ 😛

**Comment by gdude2002** [comment]
Since this has already been merged, here's some JSLint for you. http://bamboo.gserv.me/browse/GSPP-SHINE/latest

**Pull request merged**
